# Generated by Django 3.2.8 on 2024-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_extr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=255, unique=True)),
                ('BuyerFirstName', models.CharField(max_length=255)),
                ('BuyerLastName', models.CharField(max_length=255)),
                ('BuyerAddress', models.CharField(max_length=255)),
                ('BuyerCity', models.CharField(max_length=255)),
                ('BuyerState', models.CharField(max_length=255)),
                ('BuyerZipcode', models.CharField(max_length=20)),
                ('SellerFirstName', models.CharField(max_length=255)),
                ('SellerLastName', models.CharField(max_length=255)),
                ('SellerAddress', models.CharField(max_length=255)),
                ('SellerCity', models.CharField(max_length=255)),
                ('SellerState', models.CharField(max_length=255)),
                ('SellerZipcode', models.CharField(max_length=20)),
                ('PropertyDetailsAddress', models.CharField(max_length=255)),
                ('PropertyDetailsLot', models.CharField(max_length=50)),
                ('PropertyDetailsBlock', models.CharField(max_length=50)),
            ],
        ),
    ]
